default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  host: localhost
  username: postgres
  password:
  database: jobworks-dev

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:JOBWORKS_HOST) %>
  username: <%= Rails.application.credentials.dig(:JOBWORKS_USERNAME) %>
  password: <%= Rails.application.credentials.dig(:JOBWORKS_DATABASE_PASSWORD) %>
  database: <%= Rails.application.credentials.dig(:JOBWORKS_DATABASE_NAME) %>