default: &default
  adapter: postgresql
  encoding: unicode
  # username: <%= Rails.application.credentials.dig(:database, :username)  %>
  # password: <%= Rails.application.credentials.dig(:database, :password)  %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: jobworks-dev

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: jobworks_production
  pool: 5
